# Generated by Django 3.1.14 on 2022-09-22 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('name', models.CharField(max_length=10, verbose_name='강사 이름')),
                ('description', models.TextField(blank=True, default='', verbose_name='강사 소개')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사 신청자')),
            ],
            options={
                'db_table': 'master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('title', models.CharField(max_length=50, verbose_name='강의 제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='강의 상세')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentshub.master', verbose_name='강사')),
            ],
            options={
                'db_table': 'klass',
                'ordering': ['-created_at'],
            },
        ),
    ]
